server:
  port: 8080

spring:
  application:
    name: AskBase

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/askbase
    username: postgres
    password: postgres

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

askbase:
  jwt:
      secret: K8mNpQrS2vX9wYzA3bCdEfGhIjKlMnOpQrStUvWxYz0123456789ABCDEFGH+/IJKLMNOPQRSTUVWXYZ
      expire-seconds: 86400